=== foggy-ezh/WebProject/data/flowers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.epam.com/flowers"
	xmlns:tns="http://www.epam.com/flowers"
	elementFormDefault="qualified">
    <element name="flower" type="tns:FlowerType" abstract="true"/>
    <element name="outdoor-flower" type="tns:OutdoorFlower" substitutionGroup="tns:flower"/>
    <element name="indoor-flower" type="tns:IndoorFlower" substitutionGroup="tns:flower"/>
	<element name="flowers">
		<complexType>
			<sequence>
				<element ref="tns:flower" minOccurs="1" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="FlowerType">
        <sequence>
        	<element name="origin" type="string"/>
            <element name="soil" type="tns:SoilType"/>
            <element name="parameters" type="tns:Parameters"/>
            <element name="multiplying" type="tns:Multiplying"/>
        </sequence>
        <attribute name="name" type="tns:Name" use="required"/>
    </complexType>
    <simpleType name="Name">
        <restriction base="ID">
            <pattern value="[a-zA-Z_0-9]{2,}"/>
        </restriction>
    </simpleType>
    <complexType name="Parameters">
        <sequence>
            <element name="stem-color" type="string"/>
            <element name="leaf-color" type="string"/>
            <element name="avg-size" type="tns:PositiveDecimal" default="0"/>
        </sequence>
    </complexType>
    <simpleType name="PositiveDecimal">
        <restriction base="decimal">
            <minInclusive value="0" />
        </restriction>
    </simpleType>
    <simpleType name="SoilType">
        <restriction base="string">
            <enumeration value="podzolic"/>
            <enumeration value="dirt"/>
            <enumeration value="sod-podzolic"/>
        </restriction>
    </simpleType>
    <simpleType name="Multiplying">
        <restriction base="string">
            <enumeration value="leaves"/>
            <enumeration value="cuttings"/>
            <enumeration value="seeds"/>
        </restriction>
    </simpleType>
    <complexType name="OutdoorFlower">
        <complexContent>
            <extension base="tns:FlowerType">
                <sequence>
                    <element name="blooming-period" type="tns:BloomingPeriodType" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <simpleType name="BloomingPeriodType">
        <restriction base="string">
            <enumeration value="winter"/>
            <enumeration value="spring"/>
            <enumeration value="summer"/>
            <enumeration value="autumn"/>
        </restriction>
    </simpleType>
    <complexType name="IndoorFlower">
        <complexContent>
            <extension base="tns:FlowerType">
                <sequence>
                    <element name="growing-tips" type="tns:GrowingTips" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>
    <complexType name="GrowingTips">
        <sequence>
            <element name="temperature" type="decimal" default="0"/>
            <element name="required-lighting" type="tns:LightingType"/>
            <element name="water-need" type="tns:PositiveDecimal" default="0"/>
        </sequence>
    </complexType>
    <simpleType name="LightingType">
        <restriction base="string">
            <enumeration value="sun"/>
            <enumeration value="neutral"/>
            <enumeration value="shade"/>
        </restriction>
    </simpleType>
</schema>

=== foggy-ezh/WebProject/data/flowers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.epam.com/flowers"
        xsi:schemaLocation="http://www.epam.com/flowers flowers.xsd">
    <indoor-flower name="Cactus">
        <origin>America</origin>
        <soil>dirt</soil>
        <parameters>
            <stem-color>green</stem-color>
            <leaf-color>green</leaf-color>
            <avg-size>35</avg-size>
        </parameters>
        <multiplying>seeds</multiplying>
        <growing-tips>
            <temperature>+15</temperature>
            <required-lighting>sun</required-lighting>
            <water-need>10</water-need>
        </growing-tips>
    </indoor-flower>
    <outdoor-flower name="Begonia">
        <origin>Africa</origin>
        <soil>dirt</soil>
        <parameters>
            <stem-color>red</stem-color>
            <leaf-color>green</leaf-color>
            <avg-size>44</avg-size>
        </parameters>
        <multiplying>cuttings</multiplying>
        <blooming-period>summer</blooming-period>
    </outdoor-flower>
</flowers>
